spamwords = [
"#1",
"$$$",
"100%",
"100% free",
"100% Satisfied",
"4U",
"50% off",
"Accept credit cards",
"Acceptance",
"Access",
"Accordingly",
"Act Now!",
"Action",
"Ad",
"Additional income",
"Addresses on CD",
"Affordable",
"All natural",
"All natural/new",
"All new",
"Amazed",
"Amazing",
"Apply now",
"Apply Online",
"As seen on",
"Auto email removal",
"Avoid",
"Avoid bankruptcy",
"Bargain",
"Be amazed",
"Be your own boss",
"Being a member",
"Beneficiary",
"Best price",
"Beverage",
"Big bucks",
"Bill 1618",
"Billing",
"Billion",
"Bonus",
"Boss",
"Brand new pager",
"Bulk email",
"Buy",
"Buy direct",
"Buying judgments",
"Cable converter",
"Call",
"Call free",
"Call now",
"Calling creditors",
"Can’t live without",
"Cancel",
"Cancel at any time",
"Cannot be combined with any other offer",
"Cards accepted",
"Cash",
"Cash bonus",
"Casino",
"Celebrity",
"Cents on the dollar",
"Certified",
"Chance",
"Cheap",
"Check",
"Check or money order",
"Claims",
"Clearance",
"Click",
"Click below",
"Click here",
"Click to remove",
"Collect",
"Collect child support",
"Compare rates",
"Compete for your business",
"Confidentially on all orders",
"Congratulations",
"Consolidate your debt",
"Copy accurately",
"Copy DVDs",
"Cost",
"Costs",
"Credit",
"Credit bureaus",
"Credit card offers",
"Cures",
"Cures baldness",
"Deal",
"Dear",
"Debt",
"Diagnostics",
"Dig up dirt on friends",
"Direct email",
"Direct marketing",
"Discount",
"Do it today",
"Don’t delete",
"Don’t hesitate",
"Dormant",
"Double your cash",
"Double your income",
"Drastically reduced",
"Earn",
"Earn $",
"Earn extra cash",
"Earn per week",
"Easy terms",
"Eliminate bad credit",
"Eliminate debt",
"Email harvest",
"Email marketing",
"Exclusive deal",
"Expect to earn",
"Expire",
"Explode your business",
"Extra",
"Extra cash",
"Extra income",
"F r e e",
"Fantastic",
"Fantastic deal",
"Fast cash",
"Financial freedom",
"Financially independent",
"For free",
"For instant access",
"For just $xxx",
"For Only",
"For you",
"Form",
"Free",
"Free access",
"Free cell phone",
"Free consultation",
"Free DVD",
"Free gift",
"Free grant money",
"Free hosting",
"Free info",
"Free installation",
"Free Instant",
"Free investment",
"Free leads",
"Free membership",
"Free money",
"Free offer",
"Free preview",
"Free priority mail",
"Free quote",
"Free sample",
"Free trial",
"Free website",
"Freedom",
"Friend",
"Full refund",
"Get it now",
"Get out of debt",
"Get paid",
"Get started now",
"Gift certificate",
"Give it away",
"Giving away",
"Great",
"Great offer",
"Guarantee",
"Guaranteed",
"Have you been turned down?",
"Hello",
"Hidden",
"Hidden assets",
"Hidden charges",
"Home based business",
"Home employment",
"Homebased business",
"Human growth hormone",
"If only it were that easy",
"Important information regarding",
"In accordance with laws",
"Income",
"Income from home",
"Increase sales",
"Increase traffic",
"Increase your sales",
"Incredible deal",
"Info you requested",
"Information you requested",
"Instant",
"Insurance",
"Internet marketing",
"Investment",
"Investment decision",
"It’s effective",
"Join millions of Americans",
"Junk",
"Laser printer",
"Leave",
"Legal",
"Life",
"Life Insurance",
"Lifetime",
"Limited",
"Limited time offer",
"Limited time only",
"Loans",
"Long distance phone offer",
"Lose weight",
"Lower interest rates",
"Lower monthly payment",
"Lower your mortgage rate",
"Lowest insurance rates",
"Lowest Price",
"Luxury",
"Luxury car",
"Mail in order form",
"Maintained",
"Make $",
"Make money",
"Marketing",
"Marketing solutions",
"Mass email",
"Medicine",
"Medium",
"Meet singles",
"Member",
"Member stuff",
"Message contains disclaimer",
"Million",
"Million dollars",
"Miracle",
"MLM",
"Money",
"Money back",
"Money making",
"Month trial offer",
"More Internet Traffic",
"Mortgage",
"Mortgage rates",
"Multi-level marketing",
"Name brand",
"Never",
"New customers only",
"New domain extensions",
"Nigerian",
"No age restrictions",
"No catch",
"No claim forms",
"No cost",
"No credit check",
"No credit check/experience",
"No disappointment",
"No experience",
"No fees",
"No gimmick",
"No hidden",
"No hidden Costs",
"No interests",
"No inventory",
"No investment",
"No medical exams",
"No middleman",
"No obligation",
"No purchase necessary",
"No questions asked",
"No selling",
"No strings attached",
"Not intended",
"Not junk",
"Not spam",
"Notspam",
"Now",
"Now only",
"Obligation",
"Offer",
"Offer expires",
"Offshore",
"Once in lifetime",
"One hundred percent free",
"One hundred percent guaranteed",
"One time",
"One time mailing",
"Online biz opportunity",
"Online degree",
"Online marketing",
"Online pharmacy",
"Only",
"Only $",
"Open",
"Opportunity",
"Opt in",
"Order now",
"Order shipped by",
"Order status",
"Order today",
"Orders shipped by",
"Outstanding values",
"Passwords",
"Pennies a day",
"Per day",
"Per week",
"Performance",
"Phone",
"Please",
"Please read",
"Potential earnings",
"Pre-approved",
"Presently",
"Price",
"Print form signature",
"Print out and fax",
"Priority mail",
"Prize",
"Prizes",
"Problem",
"Produced and sent out",
"Profits",
"Promise",
"Promise you",
"Purchase",
"Pure Profits",
"Quote",
"Rates",
"Real thing",
"Refinance",
"Refinance home",
"Refund",
"Removal",
"Removal instructions",
"Removes wrinkles",
"Request",
"Requires initial investment",
"Reserves the right",
"Reverses aging",
"Risk free",
"Rolex",
"Round the world",
"S 1618",
"Safeguard notice",
"Sale",
"Sales",
"Sample",
"Satisfaction",
"Satisfaction guaranteed",
"Save",
"Save $",
"Save big money",
"Save up to",
"Score",
"Search engine listings",
"Search engines",
"Section 301",
"See for yourself",
"Sent in compliance",
"Serious",
"Serious cash",
"Serious only",
"Shopper",
"Shopping spree",
"Sign up free today",
"Social security number",
"Solution",
"Spam",
"Special promotion",
"Stainless steel",
"Stock alert",
"Stock disclaimer statement",
"Stock pick",
"Stop",
"Stop snoring",
"Strong buy",
"Stuff on sale",
"Subject to cash",
"Subject to credit",
"Subscribe",
"Success",
"Supplies",
"Supplies are limited",
"Take action",
"Take action now",
"Talks about hidden charges",
"Talks about prizes",
"Teen",
"Terms",
"Terms and conditions",
"The best rates",
"The following form",
"They’re just giving it away",
"This isn’t a scam",
"This isn’t junk",
"This isn’t spam",
"This won’t last",
"Thousands",
"Time limited",
"Traffic",
"Trial",
"Undisclosed recipient",
"University diplomas",
"Unlimited",
"Unsecured credit",
"Unsecured debt",
"Unsolicited",
"Unsubscribe",
"Urgent",
"US dollars",
"Vacation",
"Vacation offers",
"Valium",
"Viagra",
"Vicodin",
"Visit our website",
"Wants credit card",
"Warranty",
"We hate spam",
"We honor all",
"Web traffic",
"Weekend getaway",
"Weight",
"Weight loss",
"What are you waiting for?",
"What’s keeping you?",
"While supplies last",
"While you sleep",
"Who really wins?",
"Why pay more?",
"Wife",
"Will not believe your eyes",
"Win",
"Winner",
"Winning",
"Won",
"Work at home",
"Work from home",
"Xanax",
"You have been selected",
"You’re a Winner!",
"Your income"
];


let inp, sentence, lowersent;

let mywords = ["dank", "cool", "wut"];
let wordstodraw = [];

function setup() {
  createCanvas(500, 2000);
  inp = createInput('');
  inp.position(0, 0);
  inp.size(200);
  button = createButton('Find Spam Words');
  button.position(86, 20);
  button.mousePressed(FindSpam);
}

function draw() {
  background(220);
   for (let i = 0; i < wordstodraw.length; i++) {
     textSize(25);
      text(wordstodraw[i], 10, 70 + (i * 30));
      fill(0, 0, 0);
   }
  DrawScore()
}

function FindSpam()
{
//  console.log('you are typing: ', this.value());
  sentence = inp.value();
  lowersent = sentence.toLowerCase();
  console.log(lowersent)

  //let index = sentence.indexOf('Hello World');



  for (let i = 0; i < spamwords.length; i++) {
    let test = lowersent.indexOf(spamwords[i].toLowerCase());
    if(test > 0 ){

      wordstodraw.push(spamwords[i]);
      console.log(spamwords[i]);
    }

}
}

function DrawScore()
{
  if(wordstodraw.length >= 7)
  {
      textSize(25);
      text("Fail", 220, 25);
      fill(0, 0, 0);
  }
  else if(wordstodraw.length > 0 && wordstodraw.length <= 3)
  {
      textSize(25);
      text("Low Risk", 220, 25);
      fill(0, 0, 0);
  }
  else if(wordstodraw.length > 3 && wordstodraw.length <= 6)
  {
      textSize(25);
      text("High Risk", 220, 25);
      fill(0, 0, 0);
  }
  else
    {
       textSize(25);
      text("Pass", 220, 25);
      fill(0, 0, 0);
    }
}
